version: '3'
services:
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
      - MONGO_USER=linnlatt
      - MONGO_PASSWORD=7012
    volumes:
      - ./:/app
      - /app/node-modules
    command: npm run dev
    
