version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=linnlatt
      - MONGO_INITDB_ROOT_PASSWORD=7012
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db: